version: "2.0"
services:
  web:
    build:
      context: .
      dockerfile: dockers/Dockerfile
    ports:
    - "80:5000"
    command: gunicorn -b 0.0.0.0:5000 main:app

  worker:
    build:
      context: .
      dockerfile: dockers/Dockerfile
    command: celery -A web.celery worker -l info
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: scanner
    ports:
    - "5432:5432"
  broker:
    image: rabbitmq
    environment:
      RABBITMQ_DEFAULT_VHOST: scanner
      RABBITMQ_DEFAULT_USER: scanner
      RABBITMQ_DEFAULT_PASS: P@ssw0rd
    ports:
    - "5672:5672"

